# Generated by Django 2.1 on 2020-02-23 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicks', models.BigIntegerField()),
                ('interactions', models.BigIntegerField()),
                ('date', models.DateField()),
                ('campaigns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertising_metrics.Campaign')),
                ('data_sources', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertising_metrics.DataSource')),
            ],
        ),
    ]
