# Generated by Django 2.1 on 2020-02-23 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertising_metrics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metric',
            old_name='campaigns',
            new_name='campaign',
        ),
        migrations.RenameField(
            model_name='metric',
            old_name='data_sources',
            new_name='data_source',
        ),
    ]
