# Generated by Django 2.1 on 2020-02-23 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertising_metrics', '0002_auto_20200223_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metric',
            old_name='interactions',
            new_name='impressions',
        ),
    ]
