# Generated by Django 2.1 on 2020-02-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising_metrics', '0003_auto_20200223_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='clicks',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='metric',
            name='impressions',
            field=models.BigIntegerField(default=0),
        ),
    ]
